name: ContinuousIntegrationFlow

on:
  push:
    branches:
      - master  # Adjust if your default branch is not 'main'
  pull_request:
    branches:
      - master  # Adjust if your default branch is not 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # The OS on which the job will run

    strategy:
      matrix:
        python-version: [3.7.1]

    steps:
      - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint app/backend/*.py

      - name: Test Backend with unittest
        run: |
          python -m unittest discover -s app/backend/tests

      - name: Compile program
        run: program

      - name: Run program
        run: program

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install project dependencies
        run: npm ci

      - name: Lint with eslint
        run: npx eslint './src/**/*.{js
