name: ContinuousIntegrationFlow

on:
  push:
    branches:
      - master  # Adjust if your default branch is not 'main'
  pull_request:
    branches:
      - master  # Adjust if your default branch is not 'main'



