name: Python Application

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger this workflow on pull request to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.x'  # Specify the Python version (latest stable)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install flask     # Install dependencies from 'requirements.txt'

    - name: Run Python application
      run: |
        python backend/app.py  # Replace with the name of your Python script




